version: "3.1"
services:
  database:
    image: mariadb:10.1
    container_name: mysite-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysite
      - MYSQL_USER=mysite
      - MYSQL_PASSWORD=password
    volumes:
      - ./datadir/:/var/lib/mysql
    ports:
      - "8083:3306"
  web:
    image: apache-php
    container_name: mysite
    volumes:
      - ./src/:/var/www/html
    ports:
      - "81:80"