version: "3.1"
services:
  web:
    build:
      context:
    image: php:7.2.1-apache
    container_name: web
    volumes:
      - ../src:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php-docker.ini
    links:
      - 'database'
  database:
    image: mariadb:10.1
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysite
      - MYSQL_USER=mysite
      - MYSQL_PASSWORD=password
    volumes:
      - ../datadir/:/var/lib/mysql
